/******************************************************************************/
/*            Generated by IBExpert 2017.8.8.1 20/08/2017 22:20:46            */
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files\Firebird\firebird_2_1_dll_32bits\fbclient.dll';

CREATE DATABASE 'F:\DESENVOLVIMENTO\Delphi\Projetos\Outros\Projeto - Abastecimento Posto Combustivel\DataBase\POSTO_COMBUSTIVEL.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252;



/******************************************************************************/
/*                                 Generators                                 */
/******************************************************************************/

CREATE GENERATOR GEN_ABASTECIMENTOS_ID;
SET GENERATOR GEN_ABASTECIMENTOS_ID TO 29;

CREATE GENERATOR GEN_BOMBAS_ID;
SET GENERATOR GEN_BOMBAS_ID TO 4;

CREATE GENERATOR GEN_TANQUES_ID;
SET GENERATOR GEN_TANQUES_ID TO 2;



/******************************************************************************/
/*                                   Tables                                   */
/******************************************************************************/



CREATE TABLE ABASTECIMENTOS (
    ABASTECIMENTO  INTEGER NOT NULL,
    DATA           DATE NOT NULL,
    BOMBA          INTEGER NOT NULL,
    VALOR_BRUTO    NUMERIC(15,2) NOT NULL,
    IMPOSTO        NUMERIC(15,2) NOT NULL,
    VALOR_LIQUIDO  NUMERIC(15,2) NOT NULL,
    QUANTIDADE     NUMERIC(15,2) NOT NULL
);

CREATE TABLE BOMBAS (
    BOMBA      INTEGER NOT NULL,
    DESCRICAO  VARCHAR(100),
    TANQUE     INTEGER
);

CREATE TABLE TANQUES (
    TANQUE     INTEGER NOT NULL,
    DESCRICAO  VARCHAR(100) NOT NULL
);



/******************************************************************************/
/*                                Primary keys                                */
/******************************************************************************/

ALTER TABLE ABASTECIMENTOS ADD CONSTRAINT PK_ABASTECIMENTOS PRIMARY KEY (ABASTECIMENTO);
ALTER TABLE BOMBAS ADD CONSTRAINT PK_BOMBAS PRIMARY KEY (BOMBA);
ALTER TABLE TANQUES ADD CONSTRAINT PK_TANQUES PRIMARY KEY (TANQUE);


/******************************************************************************/
/*                                Foreign keys                                */
/******************************************************************************/

ALTER TABLE ABASTECIMENTOS ADD CONSTRAINT FK_ABASTECIMENTOS_1 FOREIGN KEY (BOMBA) REFERENCES BOMBAS (BOMBA);
ALTER TABLE BOMBAS ADD CONSTRAINT FK_BOMBAS_1 FOREIGN KEY (TANQUE) REFERENCES TANQUES (TANQUE);


/******************************************************************************/
/*                                  Triggers                                  */
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/*                            Triggers for tables                             */
/******************************************************************************/



/* Trigger: ABASTECIMENTOS_BI */
CREATE TRIGGER ABASTECIMENTOS_BI FOR ABASTECIMENTOS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.abastecimento is null) then
    new.abastecimento = gen_id(gen_abastecimentos_id,1);
end
^

/* Trigger: BOMBAS_BI */
CREATE TRIGGER BOMBAS_BI FOR BOMBAS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.bomba is null) then
    new.bomba = gen_id(gen_bombas_id,1);
end
^

/* Trigger: TANQUES_BI */
CREATE TRIGGER TANQUES_BI FOR TANQUES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.tanque is null) then
    new.tanque = gen_id(gen_tanques_id,1);
end
^
SET TERM ; ^

